name: C/C++ Nightly ubuntu-GTK2

on:
  push:
    branches:
      - Nigthly
      - nightly_dev
      - nightly_master
      - debug_ubuntu

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.16.x'
    - name: update submodule profiles
      working-directory: ./resources/profiles
      run: git submodule update --init
    - name: change date in version
      run: sed -i "s/+UNKNOWN/-$(date '+%F')/" version.inc
    - name: update clock
      run: sudo hwclock -s
    - name: update apt
      run: sudo apt update
    - name: install gtk2
      run: sudo apt install libgtk2.0-dev
    - name: install libs
      run: sudo ./BuildLinux.sh -u
    - name: dep cache
      id: cache-action
      uses: actions/cache@v3
      with:
        key: ubu_gtk2_2.7
        path: deps/build/destdir
    - if: steps.cache-action.outputs.cache-hit != 'true'
      name: build deps if new cache
      run: ./BuildLinux.sh -gd
    - name: slicer, tar & appimage
      run: ./BuildLinux.sh -gsi
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nightly_${{ github.event.repository.name }}-linux-x64-GTK2.tgz
        path: build/${{ github.event.repository.name }}-linux-x64-GTK2.tgz
    - name: Upload appimage
      uses: actions/upload-artifact@v4
      with:
        name: nightly_${{ github.event.repository.name }}-linux-x64-GTK2.AppImage
        path: build/${{ github.event.repository.name }}-linux-x64-GTK2.AppImage
