name: C/C++ Release candidate macos

on:
  push:
    branches:
      - rc

jobs:
  build_dep:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: mkdir in deps
      run: mkdir deps/build
    - name: dep cache
      id: cache-action
      uses: actions/cache@v3
      with:
        key: macos_intel_2.7
        path: deps/build/destdir
    - if: steps.cache-action.outputs.cache-hit != 'true'
      name: build deps if new cache
      run: ./BuildMacOS.sh -d

  build:
    runs-on: macos-12
    needs: build_dep

    steps:
    - uses: actions/checkout@v3
    - name: update submodule profiles
      working-directory: ./resources/profiles
      run: git submodule update --init
    - name: dep cache
      id: cache-action
      uses: actions/cache@v3
      with:
        key: macos_intel_2.7
        path: deps/build/destdir
    - name: build slicer
      run: ./BuildMacOS.sh -si
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rc_${{ github.event.repository.name }}-macOS.tgz
        path: build/${{ github.event.repository.name }}-macOS-intel.tgz
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rc_${{ github.event.repository.name }}-macOS.dmg
        path: build/${{ github.event.repository.name }}-macOS-intel.dmg
